//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package button

import (
	auth "github.com/loft-sh/license-api/auth"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Button) DeepCopyInto(out *Button) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Button.
func (in *Button) DeepCopy() *Button {
	if in == nil {
		return nil
	}
	out := new(Button)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestInput) DeepCopyInto(out *RequestInput) {
	*out = *in
	if in.InstanceToken != nil {
		in, out := &in.InstanceToken, &out.InstanceToken
		*out = new(auth.InstanceToken)
		**out = **in
	}
	out.RequestInputFrontEnd = in.RequestInputFrontEnd
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestInput.
func (in *RequestInput) DeepCopy() *RequestInput {
	if in == nil {
		return nil
	}
	out := new(RequestInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestInputFrontEnd) DeepCopyInto(out *RequestInputFrontEnd) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestInputFrontEnd.
func (in *RequestInputFrontEnd) DeepCopy() *RequestInputFrontEnd {
	if in == nil {
		return nil
	}
	out := new(RequestInputFrontEnd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestOutput) DeepCopyInto(out *RequestOutput) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestOutput.
func (in *RequestOutput) DeepCopy() *RequestOutput {
	if in == nil {
		return nil
	}
	out := new(RequestOutput)
	in.DeepCopyInto(out)
	return out
}
