//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package auth

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceToken) DeepCopyInto(out *InstanceToken) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceToken.
func (in *InstanceToken) DeepCopy() *InstanceToken {
	if in == nil {
		return nil
	}
	out := new(InstanceToken)
	in.DeepCopyInto(out)
	return out
}
