//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package licenseapi

import (
	license "github.com/loft-sh/license-api/pkg/license"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ButtonActionInput) DeepCopyInto(out *ButtonActionInput) {
	*out = *in
	if in.InstanceTokenAuth != nil {
		in, out := &in.InstanceTokenAuth, &out.InstanceTokenAuth
		*out = new(InstanceTokenAuth)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ButtonActionInput.
func (in *ButtonActionInput) DeepCopy() *ButtonActionInput {
	if in == nil {
		return nil
	}
	out := new(ButtonActionInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ButtonActionOutput) DeepCopyInto(out *ButtonActionOutput) {
	*out = *in
	if in.Buttons != nil {
		in, out := &in.Buttons, &out.Buttons
		*out = make([]license.Button, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ButtonActionOutput.
func (in *ButtonActionOutput) DeepCopy() *ButtonActionOutput {
	if in == nil {
		return nil
	}
	out := new(ButtonActionOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceCreateInput) DeepCopyInto(out *InstanceCreateInput) {
	*out = *in
	if in.InstanceTokenAuth != nil {
		in, out := &in.InstanceTokenAuth, &out.InstanceTokenAuth
		*out = new(InstanceTokenAuth)
		**out = **in
	}
	if in.AllocatedResources != nil {
		in, out := &in.AllocatedResources, &out.AllocatedResources
		*out = make(map[string]license.ResourceQuantity, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceCreateInput.
func (in *InstanceCreateInput) DeepCopy() *InstanceCreateInput {
	if in == nil {
		return nil
	}
	out := new(InstanceCreateInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceCreateOutput) DeepCopyInto(out *InstanceCreateOutput) {
	*out = *in
	if in.License != nil {
		in, out := &in.License, &out.License
		*out = new(license.License)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceCreateOutput.
func (in *InstanceCreateOutput) DeepCopy() *InstanceCreateOutput {
	if in == nil {
		return nil
	}
	out := new(InstanceCreateOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceTokenAuth) DeepCopyInto(out *InstanceTokenAuth) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceTokenAuth.
func (in *InstanceTokenAuth) DeepCopy() *InstanceTokenAuth {
	if in == nil {
		return nil
	}
	out := new(InstanceTokenAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntercomHashCreateInput) DeepCopyInto(out *IntercomHashCreateInput) {
	*out = *in
	if in.InstanceTokenAuth != nil {
		in, out := &in.InstanceTokenAuth, &out.InstanceTokenAuth
		*out = new(InstanceTokenAuth)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntercomHashCreateInput.
func (in *IntercomHashCreateInput) DeepCopy() *IntercomHashCreateInput {
	if in == nil {
		return nil
	}
	out := new(IntercomHashCreateInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntercomHashCreateOutput) DeepCopyInto(out *IntercomHashCreateOutput) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntercomHashCreateOutput.
func (in *IntercomHashCreateOutput) DeepCopy() *IntercomHashCreateOutput {
	if in == nil {
		return nil
	}
	out := new(IntercomHashCreateOutput)
	in.DeepCopyInto(out)
	return out
}
